[package]
name = "vibenet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
artnet_protocol = "0.4"
enum_dispatch = "0.3"
palette = "0.6"
serde = { version = "1.0.137", features = ["derive"] }
